### ISSUE TITLE
Fix Layout

### ISSUE THREAD

**Issue by dristi-sigdel** [subin123khanal/Library#1]
Layout Needs to be fixed in correct proportion for all pcs and mobile devices.

![image](https://user-images.githubusercontent.com/81402784/114822924-808fa780-9de2-11eb-9662-4327a7c07a54.png)

**Comment by subin123khanal** [comment]
![image](https://user-images.githubusercontent.com/81403189/114824462-a0c06600-9de4-11eb-8db8-3a031854268b.png)
 
the layout of book post that was assigned to me was solve as in the above screenshot provided.

**Comment by dristi-sigdel** [comment]
Yo chai issue fix gareko ho haina?
