### ISSUE TITLE
Book Post Interface

### ISSUE THREAD

**Issue by DanishAzeema** [subin123khanal/Library#3]
@saman-des  (Mr. Saman Tamrakar) Can you please improve the book post interface.
![bookpost](https://user-images.githubusercontent.com/81403168/114905597-d8f19400-9e38-11eb-8af3-4b987d1e0d7f.png)

**Comment by saman-des** [comment]
![image](https://user-images.githubusercontent.com/59384040/114987256-adac8a80-9eb4-11eb-9465-d2c02b8c3dd7.png)

![image](https://user-images.githubusercontent.com/59384040/114987272-b3a26b80-9eb4-11eb-98f0-445f12ba80f1.png)

I have made changes to the interface as per Danish Khan and also made the web page responsive.
